<script lang="ts">
	let { chart, title }: { chart: string; title: string } = $props();

	let svg = $state('');
	let failed = $state(false);
	const id = `mermaid-${Math.random().toString(36).slice(2, 10)}`;

	// Mermaid touches `document` at import time, so it is imported dynamically and only inside
	// the effect (client-only) -- same reason `sigma` is dynamically imported elsewhere.
	$effect(() => {
		const source = chart;
		let cancelled = false;
		(async () => {
			try {
				const { default: mermaid } = await import('mermaid');
				mermaid.initialize({
					startOnLoad: false,
					securityLevel: 'strict',
					theme: 'neutral',
					flowchart: { htmlLabels: false, useMaxWidth: true }
				});
				const result = await mermaid.render(id, source);
				if (!cancelled) {
					svg = result.svg;
					failed = false;
				}
			} catch {
				if (!cancelled) failed = true;
			}
		})();
		return () => {
			cancelled = true;
		};
	});
</script>

<figure class="mermaid-figure my-4">
	{#if failed}
		<p class="text-body-secondary small">The diagram could not be rendered.</p>
		<pre class="small"><code>{chart}</code></pre>
	{:else if svg}
		<div class="mermaid-svg overflow-auto" role="img" aria-label={title}>
			<!-- eslint-disable-next-line svelte/no-at-html-tags -- generated by mermaid (strict mode) from our own static strings -->
			{@html svg}
		</div>
	{:else}
		<p class="text-body-secondary small">Loading diagram…</p>
	{/if}
	<figcaption class="small text-secondary text-center mt-2">{title}</figcaption>
</figure>
